### ISSUE TITLE
missing CSV files

### ISSUE THREAD

**Issue by jtatfranklin** [carderne/leaflet-gsheets#1]
Your instructions state "To get started, fork this repo and use the .CSV files in the data-sources folder as examples to create the Google Sheets ..." but there are no CSV files in your repository upon which to model my Google Sheet. Thanks!

**Comment by carderne** [comment]
@jtatfranklin Have updated the README and added links the Google Sheets so you should be able to just duplicate those directly in your Google account. Please update your fork and let me know if it works! (Don't forget to share, publish and copy-paste your new Sheets URLs.)
