### ISSUE TITLE
spelling typo of "poylgonStyle" variable

### ISSUE THREAD

**Issue by jtatfranklin** [carderne/leaflet-gsheets#2]
It works because the variable is misspelled three times, but it did cause a little confusion for me.
Line 111, 118
and Line 138

**Comment by carderne** [comment]
Fixed in [Fix poylgon typo](https://github.com/carderne/leaflet-gsheets/commit/95f2da41ccc3999d33f2889a9971adbf36e16fb2).

Thanks!
