### ISSUE TITLE
developing locally

### ISSUE THREAD

**Issue by mattarderne** [carderne/leaflet-gsheets#9]
How to develop locally? Browser complains about CORS amongst others
![image](https://user-images.githubusercontent.com/23472325/159120007-d0fac32a-e9ff-43aa-be46-10e947e144b2.png)

(map loads but the Google sheets data is not imported)

**Comment by carderne** [comment]
CORS doesn't let you mix-and-match with `file:` and `http:` URLs.

Have updated the README instructions in https://github.com/carderne/leaflet-gsheets/commit/c1315e49d424903fbbc91d469003ca5ddd8cd323:

### Instructions

9. Run a local server. First make sure you're in the directory containing index.html etc, and then run:
```bash
python3 -m http.server
```
10. Then open the URL it provides (probably http://0.0.0.0:8000) in a browser!

**Comment by mattarderne** [comment]
Thanks!
